export type AppPagesType = "dashboard" 
| "profile"
| "homeworks"
| "mathscore"
| "viewer"
| "verify_email"
| "change_nickname"
| "change_email"

export type ViewerPagesTypes = "circle_area_formula" 
| "triangle_area_formula"